{% if GIT_DESCRIBE_NUMBER > '0' %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] + '.post' + GIT_DESCRIBE_NUMBER %}
{% else %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] %}
{% endif %}
{% set PKG_NAME = 'conda-helpers' %}
{% set MODULE_NAME = PKG_NAME.replace('-', '_') %}
package:
  name: {{ PKG_NAME }}
  version: {{ GIT_VERSION }}

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  noarch: python
  entry_points:
    - condac = conda_helpers.__main__:main

requirements:
  build:
    - python >=3.8
    - backports.shutil_get_terminal_size
    - colorama
    - joblib
    - path-helpers
    - pydash
    - pyyaml
    - ruamel.yaml
    - whichcraft
  run:
    - python >=3.8
    - backports.shutil_get_terminal_size
    - colorama
    - git
    - joblib
    - path-helpers
    - pydash
    - pyyaml
    - ruamel.yaml
    - whichcraft

test:
  imports:
    - {{ MODULE_NAME }}
  commands:
    - condac -h
    - condac render -h
    - condac build -h

about:
  home: https://github.com/sci-bots/{{ PKG_NAME }}
  summary: Helper functions, etc. for Conda environments.
  license: BSD

source:
#  git_url: ../
  path: ..