{% if GIT_DESCRIBE_NUMBER > '0' %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] + '.post' + GIT_DESCRIBE_NUMBER %}
{% else %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] %}
{% endif %}
# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../

package:
  name: conda-helpers
  version: {{ GIT_VERSION }}

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  noarch: python
  entry_points:
    - condac = conda_helpers.__main__:main

requirements:
  build:
    - colorama
    - joblib
    - path_helpers >=0.7
    - pyyaml
    #: .. versionadded:: 0.13
    - six
    #: .. versionadded:: 0.15
    - trollius

  run:
    - colorama
    - joblib
    - path_helpers >=0.7
    - pyyaml
    #: .. versionadded:: 0.13
    - six
    #: .. versionadded:: 0.15
    - trollius

test:
  imports:
    - conda_helpers
  commands:
    - condac -h
    - condac render -h
    - condac build -h
